language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn install
  - yarn build
deploy:
  provider: s3
  access_key_id: "AKIAJX5QDRAKU4V5L24Q"
  secret_access_key: "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"
  bucket: "vmaly-travis-test"
  region: "us-east-1"
  local_dir: ./build
  skip_cleanup: true
branches:
  only:
    - master
